### ISSUE TITLE
handle control characters  

### ISSUE THREAD

**Issue by telzul** [rsl/stringex#174]
"test\u0003test".to_url
    =>test\x03test"

i have crawled data that for some reason has \u0003 used within their text. It happens that they also use it in their title; as these chars \u0000 - \u001f are not human readable characters, could they be removed from the result?

**Comment by senotrusov** [comment]
This is indeed the issue. Recently I had a case with surprising input:
```
"Jörg Immendor\u0014. Les théâtres de la peinture"
```
and with the help of stringex it was turned to:
```
"jorg-immendor\x14-les-theatres-de-la-peinture"
```

**Comment by rsl** [comment]
sure. pull request welcome. sorry for slow reply. my inbox is... yeah. that.

**Comment by tamaloa** [comment]
any chance of PR #178 being merged and a new gem version release any time soon?

**Comment by rsl** [comment]
new gem out there now. thanks for reminding me
