### ISSUE TITLE
Freeze the Dot character

### ISSUE THREAD

**Issue by Fred-JulieDesk** [rsl/stringex#180]
Hello,

Would it be possible to freeze the "." character in the master release of this gem?

The memory allocation of this character greatly increase memory usage of some applications making extensive usage of translations.

Without freezing the character:
![capture d ecran 2016-02-08 a 14 17 31](https://cloud.githubusercontent.com/assets/13829806/12886614/1c76c924-ce6f-11e5-9368-13b45203b1b2.png)

![capture d ecran 2016-02-08 a 14 23 54](https://cloud.githubusercontent.com/assets/13829806/12886711/a2bb7034-ce6f-11e5-8ec2-4d8002e59edd.png)

With the freezing:

![capture d ecran 2016-02-08 a 14 25 08](https://cloud.githubusercontent.com/assets/13829806/12886742/cc61d73e-ce6f-11e5-8b15-3c45c17fa157.png)

With only this change in my application I have seen a decrease in the memory allocated of at least 5 MB (don't know if the displayed informations are in bits or bytes to be honest. I assumed it is in bits)

I wanted to perform a pull request but i can't figure out how to do it, so could you please do it yourself?
I am sure it would help lots of people who might not have even noticed this problem.

Have a nice day,

**Comment by Darep** [comment]
Just happened to notice this issue while investigating some issues in our app and decided to give a helping hand with the pull request, see #181 :)

**Comment by Fred-JulieDesk** [comment]
cool thx, can you explain me in a few words how you did the pull request from my fork?

ty,

**Comment by Fred-JulieDesk** [comment]
i found it, nevermind

thx for the help

Have a nice day,

I close this issue

**Comment by Darep** [comment]
You're welcome! :)
