### ISSUE TITLE
request to follow SemVer/mention it in README

### ISSUE THREAD

**Issue by pravi** [rsl/stringex#188]
Do you follow Semantic Versioning http://semver.org? If yes, can this be mentioned in README? If not, can you consider it?

**Comment by rsl** [comment]
yes, not sure i follow why i have to explicitly state what kind of versioning?

**Comment by rsl** [comment]
policy to only use gems that use it or something? not a problem just honestly super curious. lol

**Comment by pravi** [comment]
@rsl because most developers are scarred about updates breaking their code and insist on exact patch releases like gollum-lib requiring ~> 2.5.1. In debian we try to keep only the latest version on a library so we are already on 2.6.0. This means we have to patch gollum-lib's gemspec. to convince gllum-lib to relax their requirement to ~> 2.5, I can tell them you follow SemVer. You might be surprised why you have to state it explicitly, but that is not the default state f affair, people don't provide backward compatibility in minor updates. I have been doing a survey https://wiki.debian.org/Teams/Ruby/UpstreamPledge see the response of sidekiq developer.

**Comment by rsl** [comment]
oh i know a lot of people don't. yeah. that sucks. does stating it help though? easy to do and nothing i have a problem with.

**Comment by rsl** [comment]
what kind of wording would help btw? feel free to make a PR adding it to readme, sure. thanks.

**Comment by rsl** [comment]
thanks on this

**Comment by rsl** [comment]
gem updated [patch version] too lol
