### ISSUE TITLE
Both asciidoctor and string_ex define String#limit()

### ISSUE THREAD

**Issue by gpakosz** [rsl/stringex#192]
`asciidoctor` just started extending the `String` class with `#limit()`.

See [`asciidoctor/core_ext/string/limit.rb`](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/core_ext/string/limit.rb#L4-L9) and https://github.com/asciidoctor/asciidoctor/issues/1889.

**Comment by rsl** [comment]
looks like this got fixed on the other side. sorry about delay. new year resolution to be more active here. :D thanks.

**Comment by gpakosz** [comment]
Except `asciidoctor` folks didn't release a `1.5.6` yet :/

**Comment by rsl** [comment]
i don't think blindly using some other library's potentially random definition of #limit works in this codebase. it's impossible to know what the definition of that method might be. someone could make #limit mean something that doesn't work in StringEx's context/needs. open to pull requests [doesn't mean i except them all, obviously hehe] so let me know if you come up with something that you think could work. thanks.

**Comment by gpakosz** [comment]
Alright.

In fact could `stringex` not define `String#limit()` in the first place? As far as I can tell, this is an implementation detail

**Comment by rsl** [comment]
that would break anyone who's actually using it so i don't think that's a great solution.
