### ISSUE TITLE
Backticks not always removed

### ISSUE THREAD

**Issue by joekur** [rsl/stringex#195]
Eg:
```ruby
"foo` bar".to_url # => "foo`-bar"
```

**Comment by joekur** [comment]
Also noticed that `~` does not get removed/escaped.

From https://www.ietf.org/rfc/rfc1738.txt:
> These [unsafe] characters are "{", "}", "|", "\", "^", "~", "[", "]", and "`".

**Comment by rsl** [comment]
good catch!
