### ISSUE TITLE
Publishing to rubygems

### ISSUE THREAD

**Issue by jocmp** [rsl/stringex#212]
After https://github.com/rsl/stringex/pull/211 it doesn't look like the [rubygems](https://rubygems.org/gems/stringex) was updated to v2.8.6.

It also looks like the link to Travis CI <https://travis-ci.org/rsl/stringex> redirects to the landing page. Is it that the CI pipeline is down?

**Comment by rsl** [comment]
had to manually do it. oh the old ways. :D

**Comment by jocmp** [comment]
so it goes. thanks!
